default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: postgres
  password: vagrant
  database: garden_plan

test:
  <<: *default
  host: localhost
  username: postgres
  password: vagrant  
  database: garden_plan_test

production:
  <<: *default
  database: garden_plan
